###
GET

###
GET 


###
POST 
Content-Type: : application/json

    {
      "id": 1,
      "title": "Vegetables",
      "food": "Lettuce",
      "stock": true,
      "price": "$2.99",
    },
    {
      "id": 2,
      "title": "Vegetables",
      "food": "Carrots",
      "stock": true,
      "price": "$1.99",
    },
    {
      "id": 3,
      "title": "Breads",
      "food": "Premium Burger Buns",
      "stock": true,
      "price": "$4.99",
    },
    {
      "id": 4,
      "title": "Meat",
      "food": "Mince",
      "stock": true,
      "price": "$12.99",
    },
    {
      "id": 5,
      "title": "SPREADS",
      "food": "Mayonnaise",
      "stock": true,
      "price": "$3.99",
    },
    {
      "id": 6,
      "title": "SPREADS",
      "food": "Premium Sauce",
      "stock": false,
      "price": "$13.99",
    }